### ISSUE TITLE
Support RBAC Configuration

### ISSUE THREAD

**Issue by abhiyerra** [opszero/auditkube#12]
# Observation

While we have support for Cluster Level Security we need to also address the Kubernetes layer of security

# Expected Result

Have a tool that can generate secure RBAC configurations for HIPAA/PCI

# Why

Currently, the default setup for Kubernetes is everything has access to everything and we want to change that.

# Blog Post

- [ ] Tell a story of the use case. Put yourself in the buyer's shoes
- [ ] The dilemma that the team sought to solve for its prospects or customers
- [ ] How are we solving it?
- [ ] What does it look like?
- [ ] How to use it?
- [ ] Reiterate the value prop

# Tasks

 - [ ] Write Blog Post
 - [ ] Build It

 - [ ] https://kubernetes.io/docs/admin/authorization/rbac/
 - [ ] Generate configurations for HIPAA/PCI that limits access so that people can't do everything but have a more limited set of things that they are allowed to do.

 - [ ] Test It
 - [ ] Release Blog
 - [ ] Release Notes (https://opszero.typeform.com/to/JMnLYH)
 - [ ] Update Weebly
 - [ ] Post on Product Hunt as New Features / Screenshots
 - [ ] Update Adwords
 - [ ] Send to Marketing Locations

**Comment by abhiyerra** [comment]
With the recent announcement of AWS EKS I believe that this is obsolete.
