### ISSUE TITLE
Setup OpenSCAP

### ISSUE THREAD

**Issue by abhiyerra** [opszero/auditkube#18]
# Observation

Need to setup OpenSCAP as it provides an interface for compliance

# Expected Result

Setup OpenSCAP as a default install on the image

# Why

OpenSCAP is a default for compliance related issues.

# Blog Post

- [ ] Tell a story of the use case. Put yourself in the buyer's shoes
- [ ] The dilemma that the team sought to solve for its prospects or customers
- [ ] How are we solving it?
- [ ] What does it look like?
- [ ] How to use it?
- [ ] Reiterate the value prop

# Tasks

 - [ ] Write Blog Post
 - [ ] Build It

 - [ ] Install OpenSCAP
 - [ ] Make sure that it exports to an appropriate location.

 - [ ] Test It
 - [ ] Release Blog
 - [ ] Release Notes (https://opszero.typeform.com/to/JMnLYH)
 - [ ] Update Website
 - [ ] Post on Product Hunt as New Features / Screenshots
