### ISSUE TITLE
Add AppCanary

### ISSUE THREAD

**Issue by cordoval** [opszero/auditkube#4]
# Observation

Have Package Level Auditing

# Expected Result

Have the nodes being checked by AppCanary as an addon.

# Why

Add additional node level security.

# Blog Post

- [ ] Tell a story of the use case. Put yourself in the buyer's shoes
- [ ] The dilemma that the team sought to solve for its prospects or customers
- [ ] How are we solving it?
- [ ] What does it look like?
- [ ] How to use it?
- [ ] Reiterate the value prop

# Tasks

 - [ ] Write Blog Post
 - [ ] Build It

 - [ ] Add AppCanary API Key
 - [ ] Create file in node.

 - [ ] Test It
 - [ ] Release Blog
 - [ ] Release Notes (https://opszero.typeform.com/to/JMnLYH)
 - [ ] Update Weebly
 - [ ] Post on Product Hunt as New Features / Screenshots
 - [ ] Update Adwords
 - [ ] Send to Marketing Locations

**Comment by cordoval** [comment]
it is not needed right? could you please add some more info?

**Comment by abhiyerra** [comment]
Well Appcanary is shutting down.
