### ISSUE TITLE
AWS CloudWatch Monitoring Scripts

### ISSUE THREAD

**Issue by abhiyerra** [opszero/auditkube#9]
# Observation

Add CloudWatch Monitoring so we can keep track of all the changes in

# Expected Result

Have AWS tracking the nodes metrics so we can see them in the AWS dashboard.

# Why

There is no insight at the moment with default kops.

# Blog Post

- [ ] Tell a story of the use case. Put yourself in the buyer's shoes
- [ ] The dilemma that the team sought to solve for its prospects or customers
- [ ] How are we solving it?
- [ ] What does it look like?
- [ ] How to use it?
- [ ] Reiterate the value prop

# Tasks

 - [ ] Write Blog Post
 - [ ] Build It

- [ ] Add cloudwatch scripts http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html
- [ ] Need to have a way of tracking those changes.

 - [ ] Test It
 - [ ] Release Blog
 - [ ] Release Notes (https://opszero.typeform.com/to/JMnLYH)
 - [ ] Update Weebly
 - [ ] Post on Product Hunt as New Features / Screenshots
 - [ ] Send to Marketing Locations
